### ISSUE TITLE
Student module (P3)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#10]
**Home->Student-> Manage Students-> Ramu K ->Update Basic Details**.

While i'm trying to update a student details, in that **Adhara number text box** accepting even 2 digits also. PFA.

![adhar_error](https://user-images.githubusercontent.com/33898399/33304378-463713ea-d3bd-11e7-8383-b7fd837db865.png)

Thanks & Regards,
Bhadra.

**Comment by pasha05** [comment]
FIXED (PASHA)

**Comment by bhadra988** [comment]
Partially fixed as it is having a problem with the copy the text from some where along with space followed by number, it is accepting as correct. But actually it should throw error message. Please refer below screen shots.
![aadhra_erro](https://user-images.githubusercontent.com/33898399/33883364-5f8d98d0-def0-11e7-830b-c72468760f7f.png)

**Comment by bhadra988** [comment]
Working fine in samsindia
