### ISSUE TITLE
Admin Login_Employee:manage employee pdf,excel getting SQL Exceptions

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#100]
In Admin login while clicking on manage employee there is a button called **pdf** while clicking on that it throws an SQL Exception like below.as well as **excel**.
**Navigation**:Home /Employee /Manage Employees
**Result**:

![emp_pdf](https://user-images.githubusercontent.com/33898412/33991770-fec7063c-e0f5-11e7-8863-da30599a18ab.png)

**Comment by pasha05** [comment]
fixed, please check

**Comment by Shiva578** [comment]
working fine but it takes time to generate PDF and excel. Excel getting college name as Sri Chitturi Indrayya Memorial Government Degree & Pg Collegememorial.

**Comment by Shiva578** [comment]
working fine
