### ISSUE TITLE
Employee module:personal info validations

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#105]
In employee **personal info** module while clicking on edit button **personal info** most of the fields accepting **special characters,****bank details account number** accepting single digit and bank details most of the fields accepting special characters please refer below screen
![personal info](https://user-images.githubusercontent.com/33898412/34242095-aeeb43a4-e63f-11e7-860e-a333c9df4fac.png)

**Comment by Shiva578** [comment]
PAN card format:first 5 characters,4 digit number 1 character.like this (CPMFG1722G)
Passport number:alphanumeric only and should be between 7 to 20 characters.
Voter Id:first 3 digits should be alpha remaining integer values it should contain at most 20 characters.
Ration card Number:(WAP0525012A0070).(show some user friendly message in this field)

Bank account number: 11 digits in SBI.
Bank name:should not allow special characters and numbers.
ifsc code: format like SBIN0001440.
micr code:should allow only 9digits.(3 digits are pin code,3 digits for bank code,3 digits for branch code).

salary info fields we will gather info from any of an employee who is working on govt dept.
pay scale: minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)
Agp: minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)
basic pay:minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)
hra: minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)
da: minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)
other allowances: minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)
total: minimum accepting 1000(4 digits) and maximum 10,00,000(7 digits)

**Comment by Shiva578** [comment]
while entering values in **personal info** text boxes it will getting **validation error within the text box while clicking on update it will throws an SQL Exception**
![image](https://user-images.githubusercontent.com/33898412/34607954-025f8f4c-f23c-11e7-9f28-ea0511b6c864.png)
while clicking on **update button** **it** throws an SQL Exception
![image](https://user-images.githubusercontent.com/33898412/34608004-37c6824e-f23c-11e7-820b-38c28610f663.png)

**Comment by Shiva578** [comment]
same above validations issues we are getting in employee personal info like below
![image](https://user-images.githubusercontent.com/33898412/34609136-70bac31c-f241-11e7-8358-026297fbb7e9.png)

**Comment by Shiva578** [comment]
**Pan card number** should display user friendly message end user may confuse if we are not providing
**Voter Id**: it accepts 1 digit value
Ration card number accepts all integer values
APGLI Number: alpha numeric max 20
GPF/CPS Number: alpha numeric max 20
EHS Card Number: alpha numeric max 20
Certificate Number:alpha numeric max 20
Bank account number accepts 1 digit only (it should allow 11 digits )

**Comment by phanibhushang** [comment]
in process

**Comment by phanibhushang** [comment]
Issue fixed.

**Comment by Shiva578** [comment]
working fine
