### ISSUE TITLE
Employee module:personal info certificate number textbox throws Sql exception 

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#110]
In employee module **personal info** tab while clicking on edit there is a field called **certificate number** whenever enter following number it throws an **SQL Exception** and also **navigation** **problem** while clicking on **cancel button** it will redirect to **Basic info**
![emp_per_certifnumber](https://user-images.githubusercontent.com/33898412/34297150-6b0381d0-e73c-11e7-8dcd-ac7bac867d63.png)
**result**:
![emp_per_cernum](https://user-images.githubusercontent.com/33898412/34297168-8e834000-e73c-11e7-83c1-4e8b92b6bde5.png)

**Comment by phanibhushang** [comment]
When we add academics row, then update button won't work, this is related to #111 . For #111, we need master data.

**Comment by Shiva578** [comment]
**Certificate number** accepts special characters like &%^$#$ and also few more fields accepts **single digit**  value,**special characters** in **bank details as well as Salary details**
![emp_personal](https://user-images.githubusercontent.com/33898412/34377810-cab4e60c-eb18-11e7-9176-65e12fe94a53.png)

**Comment by phanibhushang** [comment]
@Shiva578 : Can you provide sample format for "GPF/CPS", "EHS Card", "Certificate Number" etc...

**Comment by Shiva578** [comment]
EHS of an employee contains 3 alphabets followed by 12 digit number like  **wap188100600419**

**Comment by Shiva578** [comment]
The GPF A/c has two parts,viz. - "Series" and Number.
Series normally denotes the Department of the Employee, but it always need not be the Department.
Eg. EDN for Education, POL for Police, MEDL For Medical, AIS for All India Service, MISC for Miscellaneous, etc.

The Number is the serial number under each 'series' and is hence unique only in that series. The Series along with the Number forms the GPF Account Number of an employee.
Eg. A/c.No.MEDL/4323 can be the GPF Account No. of Shri XYZ and A/c No.POL/4323 can the GPF Account No. of Shri ABC.

**Comment by Shiva578** [comment]
working fine
