### ISSUE TITLE
Employee module:Academics & awards department test details not showing any items in drop down list

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#111]
In employee module **academic & awards** tab while clicking on **edit button** we have **department test** details column in that while clicking on **add(+)icon** it shows related fields, fill out all the fields click on **update** button it shows user friendly message, in that **drop down lists** not showing any items to select and also navigation problem while click on **cancel button** it redirecting to **basic info** present we are in **academic & awards** tab. 
![department test detalis](https://user-images.githubusercontent.com/33898412/34317798-8d2540f0-e7dc-11e7-8097-cc5dfe3b7456.png)

**Comment by phanibhushang** [comment]
Masters not available for this.

**Comment by phanibhushang** [comment]
Hari, keep some sample data(different sample data for each dropdown) for masters for issues #111 and #113.

**Comment by phanibhushang** [comment]
In Process

**Comment by Shiva578** [comment]
We are getting **SQL Exception** while clicking on **update** **button**.
![image](https://user-images.githubusercontent.com/33898412/34438839-80ba5d9e-eccf-11e7-8899-f0b58d170b88.png)

**Comment by Shiva578** [comment]
working fine
