### ISSUE TITLE
Employee module:Academic & awards publications title text box  throws SQL Exception

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#112]
In employee module **academic & awards** tab while clicking on **edit button** we have **publications** column in that we have **text box** named as **title** there is no limit for characters while entering below text it throws an SQL Exception like below.
![publications](https://user-images.githubusercontent.com/33898412/34317836-75c1aeb6-e7dd-11e7-9515-524d3d993b4b.png)

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by Shiva578** [comment]
working fine
