### ISSUE TITLE
Employee module: Academic & awards_Awards,Seminars update button not working

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#113]
In employee module **academic & awards** tab,while clicking on edit button we have **awards** column in that we have **text box** named as **title** while entering text then clicking on update button**,update button not working** (**Same issue in Seminars column**)
![awards](https://user-images.githubusercontent.com/33898412/34318257-86040380-e7e9-11e7-826f-26a909fd4c31.png)

**Comment by phanibhushang** [comment]
When we add academics row, then update button won't work, this is related to #111 . For #111, we need master data.

**Comment by phanibhushang** [comment]
Hari, keep some sample data(different sample data for each dropdown) for masters for issues #111 and #113.

**Comment by Shiva578** [comment]
Sir in that **academics & awards** tab we have another column called **qualifications** in that we have one **text box** named as **Name of the institute** it accepting more than 50 characters while clicking on **update** we are getting **SQL Exception**
![emp_qualification](https://user-images.githubusercontent.com/33898412/34400450-7e2ece8e-ebb7-11e7-9dde-47f878600322.png)

**Comment by Shiva578** [comment]
While entering **department test** details and then click on update it throws an SQL Exception like below.
![image](https://user-images.githubusercontent.com/33898412/34600328-f3c9c30e-f21c-11e7-91c4-32098325a10a.png)

**Comment by Shiva578** [comment]
while **deleting** **department test details** and then clicking on update button it shows deleted records in **academic & awards** tab
![image](https://user-images.githubusercontent.com/33898412/34637934-c5b3a6fe-f2e6-11e7-88be-056a64ed29c6.png)

**Comment by Shiva578** [comment]
working fine
