### ISSUE TITLE
Employee module:family info_nominee info name text box getting SQL Exception

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#117]
In **employee module** we have **family info tab** in that we have  **nominee information column** there is a **text box** called **name** it accepting accepting characters like jfgdfgsjfgjgfsjfgsjgfjgfjsgfjsgfjhghsfjsgfjsgfjsgfjsgfsjgfsjdhfgjfgsjgfsjfgdjfsjgfjdsgfdjsgfjsdgfjsdgfjfgjsfgsjgfsgfjsfgsjgfsjgfjfgjfgfgsgdjfgsjfgsjafkgakg **it throws an SQL Exception**

![image](https://user-images.githubusercontent.com/33898412/34429400-bf7e1734-ec7d-11e7-9c1e-018f67504069.png)

**Comment by phanibhushang** [comment]
Issue Fixed

**Comment by Shiva578** [comment]
working fine
