### ISSUE TITLE
Employee module:personal info tab_Dependent info_name getting SQL Exception

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#118]
In **employee module**  we have **family info tab** in that a column called **dependent information** we have **text box** called **name** it accepting **alpha numeric values** like below and it throws an **SQL exception**

![image](https://user-images.githubusercontent.com/33898412/34429515-26610118-ec7f-11e7-9411-8c6e2b485ea9.png)

**Comment by phanibhushang** [comment]
Issue Fixed

**Comment by Shiva578** [comment]
working fine
