### ISSUE TITLE
Employee login:login credentials index page  sometimes we are getting 404 not found error

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#123]
While entering login credentials either **employee or student it may be college profile** clicking on **login** button sometimes it shows **404 not found error.**

**Comment by Shiva578** [comment]
While **clearing cache** and then first time we are login into srr college it is going to give a error **404 not found error.**
  
![image](https://user-images.githubusercontent.com/33898412/34519336-77f012ca-f0a9-11e7-87e5-6807420c9183.png)

**Comment by phanibhushang** [comment]
I think college Id mapping issue.

**Comment by Shiva578** [comment]
enter login credentials click on login button and then clear cookie,history and then logout,again login we will get the above error

**Comment by Shiva578** [comment]
working fine
