### ISSUE TITLE
Admin login_configuration_national holiday_excel getting different college name

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#127]
In **admin login** we have a menu in that we have a tab called **configuration** while clicking on it.it display **national holiday** while clicking on it we have a button called **excel** click on it generated excel displays
**Sri Chitturi Indrayya Memorial Government Degree & Pg   College**

**Navigation**: Home /Configuration /National Holiday List

![image](https://user-images.githubusercontent.com/33898412/34474747-6c7a846c-efa9-11e7-98c1-1d572068f6e2.png)

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by Shiva578** [comment]
not yet fixed still existing in admin login

**Comment by Shiva578** [comment]
working fine
