### ISSUE TITLE
Employee Module: Employee_Basic info_Date of birth  P3 Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#13]
In Employee module if we edit  Basic info **Employee Date of Birth** it accepts **1900 year**

**navigation**: Home/Employee/ Manage Employees/ narendra k /Update Personal Details
![employee_basicinfo_dateof birth](https://user-images.githubusercontent.com/33898412/33305105-7f847b36-d432-11e7-8c2a-d9a2874a3e47.png)

**Result:**Updated in Employee date of birth like **01-11-1900**
Thanks & regards,
Shiva

**Comment by Shiva578** [comment]
All calendar issues are mentioned below please refer it once:
**Basic info tab**:
1.Employee date of birth.(age minimum 20 years)
2.Employee joining date(min age 20+years eligibility)
3.Retirement date:it should follows employee date of birth(retirement age 60)(Eg: D.O.B:2000 Retirement age:2060)

**Family info tab**:
 Dependent info:Date of birth(minimum 18)
 Nominee info:Date of birth(minimum 18)

**Personal info tab**:
  personal info:issue date(depends on the date of birth of a person may be they born with disability)
  salary info:Next increment date(depends on the joining date of an employee every year)
  
**Academics & awards**:
  Qualification:year of passing (depend on the examination conducted year).
  Orientation program: To date should be greater than from date.(once we select only from date and click 
 on update it is updated(from date and to-date must be selected once we select any of two).

**Department test Details**:
 1. Examination date
 
**Publications**:
 1. publication date

**Awards**:
 1. Receiving date.

**Seminars**:
 1.from date and to-date :To date should be greater than from date.(once we select only from date and click on update it is updated(from date and to-date must be selected once we select any of two).

**Comment by Shiva578** [comment]
partially fixed

**Comment by bhadra988** [comment]
working fine
