### ISSUE TITLE
Student module in admin login ( Excel sheet error in student status link)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#137]
In admin login excel report of student status gives the college name as Sri Chitturi Indrayya Memorial Government Degree & Pg College.

![image](https://user-images.githubusercontent.com/33898399/34512064-a665ef70-f014-11e7-8385-2839cd394271.png)

![image](https://user-images.githubusercontent.com/33898399/34512014-467632aa-f014-11e7-8191-3730beb875f5.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by bhadra988** [comment]
working good
