### ISSUE TITLE
Student module in admin login( Excel sheet error in admission category link)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#138]
In admin login, excel report of admission category gives name as Sri Chitturi Indrayya Memorial Government Degree & Pg College

![image](https://user-images.githubusercontent.com/33898399/34512110-038eb79a-f015-11e7-8d16-9fb318239d19.png)

![image](https://user-images.githubusercontent.com/33898399/34512164-5de2adf0-f015-11e7-88c3-89ac424938cb.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by bhadra988** [comment]
Working fine
