### ISSUE TITLE
In employee alc login:manage employee grid shows null values

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#139]
In  **alc college** login while clicking on **manage employee** last name  column shows **null values** 

![image](https://user-images.githubusercontent.com/33898412/34512316-984212c0-f087-11e7-8996-bb3060bb78d0.png)

**Comment by phanibhushang** [comment]
Issue fixed and restricting NULL values in Department, Designation, Category columns also

**Comment by Shiva578** [comment]
working fine
