### ISSUE TITLE
student module in admin login( Filtering wise search is not working in Reset student login link)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#140]
In admin login, when i'm selecting the reset login tab and i'm filtering the course wise list, it didn't work.

![image](https://user-images.githubusercontent.com/33898399/34512236-d2ca7bc0-f015-11e7-96cd-6dd89c735a6f.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by bhadra988** [comment]
Working fine
