### ISSUE TITLE
student module in admin login (Filtering wise search is not working in Reset password link)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#141]
In admin login, when i'm selecting the reset Password tab and i'm filtering the course wise list, it didn't work.

![image](https://user-images.githubusercontent.com/33898399/34514142-9dfb7844-f020-11e7-9a4d-db3727413513.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by bhadra988** [comment]
Working good
