### ISSUE TITLE
Employee module:Employee id text box is in editable mode

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#143]
In **employee module** while clicking on **add employee** menu,it will display add employee page in that we have **text box** called **employee id**,there is a chances to edit employee id so we will make it as **read only** (while clicking on employee basic info edit button **employee id** is also in editable mode)
![image](https://user-images.githubusercontent.com/33898412/34551079-436f2e30-f13c-11e7-94c7-ca67db09980b.png)

**Comment by phanibhushang** [comment]
Issue fixed.

**Comment by Shiva578** [comment]
While updating basic info also employee id is in editable mode we make it as read only.

**Comment by Shiva578** [comment]
working fine
