### ISSUE TITLE
Student module( Record deleted and appeared in grid, but can't find which one is deleted or not)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#146]
In manage student grid, i'm deleted a record but it displayed in manage student grid fine, but how can i identify status of that particular record is deleted or active or inactive 

![image](https://user-images.githubusercontent.com/33898399/34557564-845a3374-f0ef-11e7-8995-a6a55c76d167.png)

**Comment by phanibhushang** [comment]
issue fixed. removed delete icon for that deleted record.

**Comment by bhadra988** [comment]
working fine
