### ISSUE TITLE
Employee module:navigation issue

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#149]
**Employee module** we have different columns like **basic info,family info,address,personal info,documents,academics & awards**, we providing individual **edit button** while clicking on it it display concern page in **editable mode** while clicking on **cancel** by default it redirecting to **basic info**

**Comment by phanibhushang** [comment]
fixed for back button, let cancel button behave like present (going to first tab).

**Comment by Shiva578** [comment]
working fine
