### ISSUE TITLE
Student Module (student profile photo not uploading properly)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#15]
**Home->Student->Manage Students-> Ramu K** 

While i'm trying to upload student profile photo it's not uploading.

![pfofile photo not uploaded](https://user-images.githubusercontent.com/33898399/33305434-f32d08a2-d3c2-11e7-9b2c-d5aa75d9779c.png)
![profile photo not uploaded1](https://user-images.githubusercontent.com/33898399/33305435-f361d636-d3c2-11e7-983c-65e976d91cad.png)

Thanks & regards,
Bhadra.

**Comment by pasha05** [comment]
working properly in my Local [PASHA]

![image](https://user-images.githubusercontent.com/34034873/33391769-0d1d6312-d560-11e7-83c3-3b0bb5c73299.png)


Note : in apsams.in it is not working

**Comment by bhadra988** [comment]
Still it not working in samsindia.in

**Comment by bhadra988** [comment]
Working fine

**Comment by bhadra988** [comment]
it's not working in samsindia

**Comment by bhadra988** [comment]
It's not working properly  in samsindia.in

**Comment by bhadra988** [comment]
If uploading the profile picture, the name of the picture containing spaces, this time picture is not coming in PDF format.

**Comment by bhadra988** [comment]
Working fine
