### ISSUE TITLE
Employee module:Academic & awards update button not working but it display values in academic & awards tab

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#151]
In **employee module** we have **academic & awards** while clicking on **edit button** we have some columns,adding individual column values like **qualifications,orientation program,department test details,publications,awards,seminars** add all the concern filed and click on **update button**, **update button not working .**
![image](https://user-images.githubusercontent.com/33898412/34598429-a17e3120-f212-11e7-846c-84c76bbebb9c.png)
but **it display values like below screen** i entered only one row value in individual column in **qualification it shows 3 rows.**
![image](https://user-images.githubusercontent.com/33898412/34598469-e1db1742-f212-11e7-9c84-78ea36994684.png)

**Comment by Shiva578** [comment]
while entering department test details hall ticket number some value and then click on update it shows hall ticket number as 0

and also in qualifications  column %marks allows more than 100% like 789%

**Comment by Shiva578** [comment]
while adding all the fields in **academics & awards  update button not working** but remaing field values are not going to update.
![image](https://user-images.githubusercontent.com/33898412/34638658-8780e7c4-f2f6-11e7-91d4-f2cf2a629d56.png)

**Comment by phanibhushang** [comment]
Issue fixed.

**Comment by Shiva578** [comment]
working fine
