### ISSUE TITLE
Employee module:family info_alignment issue after updating the data

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#152]
In **employee module** we have **family info** tab we have to fill all the concerned fields like **dependent info,nominee info,spouse working info** and then click on **update** it shows alignment like below screen.
![image](https://user-images.githubusercontent.com/33898412/34598716-5d3e1c26-f214-11e7-8f74-b1ec3d2221f3.png)

**Comment by bhadra988** [comment]
working fine
