### ISSUE TITLE
Student Module (navigation Issue)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#155]
1) In student module we have different tabs like basic information, Personal, Academic, Guardian, address and Documents, if i'm clicking on edit and then click on cancel button in all tabs navigation focus on basic information tab.
2) In student module when i'm click on edit button in personal details and without updating i clicked on Back button this time also the navigation focus on basic information tab

**Comment by phanibhushang** [comment]
check once for back button. let cancel button be like that.

**Comment by bhadra988** [comment]
okay it; working fine
