### ISSUE TITLE
Employee alc login:excel getting last name as null

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#158]
In **alc login** **employee module** while clicking on **manage employee** we have **excel button** while clicking on it,it display **last name** as **null**
![image](https://user-images.githubusercontent.com/33898412/34608612-22a2a61a-f23f-11e7-86e5-7fe3693775f4.png)

**Comment by Shiva578** [comment]
In **admin login** **employee module** we have a **department** click on it it shows **department,designation,category**  page there we have excel button click on it,it shows college name like below.

**Sri Chitturi Indrayya Memorial Government Degree & Pg   College**
![image](https://user-images.githubusercontent.com/33898412/34639188-bcdb3d02-f300-11e7-9400-a7fb30a9bdd6.png)

**Comment by phanibhushang** [comment]
in process

**Comment by phanibhushang** [comment]
issue fixed, now we get all records into export.

**Comment by Shiva578** [comment]
working fine
