### ISSUE TITLE
Employee module: Employee_Basic info_joining date_P3 Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#16]
In employee module employee **_date of joining_** accepts **1900 year**

**Navigation**: Home/ Employee/ Manage Employees/ narendra k /Update Personal Details
![employee_basicinfo_joiningdate](https://user-images.githubusercontent.com/33898412/33305419-0dc5ec8a-d434-11e7-8a2e-ed5ca921fab5.png)

**_Result_**:It is updated as **_08-11-1900_**

**Comment by bhadra988** [comment]
working fine
