### ISSUE TITLE
Student module(update button problem)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#160]
1) In student academic tab i'm entered one student academics record 

![image](https://user-images.githubusercontent.com/33898399/34609259-d58da118-f1d0-11e7-968c-96f46a129d51.png)

2)and then click update button in 3 times it creates 3 records automatically. 

![image](https://user-images.githubusercontent.com/33898399/34609083-199cb138-f1d0-11e7-9cc8-8d0c51dfd891.png)

After displaying also it showing

![image](https://user-images.githubusercontent.com/33898399/34609169-66ee2f98-f1d0-11e7-8b0e-0377dae728e1.png)

**Note: **Same problem for all tabs (Stu Activities, Stu Awards, Stu Hobbies)**** 
  =========================END======================================

While i'm adding student Guardian details and click add button in multiple time Guardian details also created multiple times . Refer following screen shot

![image](https://user-images.githubusercontent.com/33898399/34709906-149c3108-f4ce-11e7-9a4f-9c95ad4ff5f2.png)

**Comment by phanibhushang** [comment]
In-process

**Comment by bhadra988** [comment]
working fine
