### ISSUE TITLE
Student Module (Not having length restriction it gives Database Exception – yii\db\Exception)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#161]
In student Basic information(Student email id) and personal( father and mother email id) tabs having 3 email id text boxes,and also add student having one email id text box, if we entered the maximum length of characters it gives **Database Exception – yii\db\Exception**, these 4 email id text boxes are not having length restrictions.(set max length of email id : 65 characters)

![image](https://user-images.githubusercontent.com/33898399/34636555-ff9a127e-f258-11e7-8512-17413006e798.png)

![image](https://user-images.githubusercontent.com/33898399/34636609-7e4e6010-f25a-11e7-9466-b5b731bdb19d.png)

**Note**
same issue for these below listed text boxes, so could you please set the maximum length of these text boxes 
**Personal detail tab->Bank Details :**
1.Bank name text box( set max length : 100 characters)
2.Branch name text box( set max length : 100 characters)

**Academic Details-tab**
1. Stu Activities->Description text box( set max length : 150 characters)
2. Stu Awards->Title text box( set max length : 100 characters)
3. Stu Awards->Description text box( set max length : 150 characters)
4. Stu Hobbies->Hobbies/Interests text box( set max length : 150 characters)
5. Stu Hobbies->Description text box( set max length : 150 characters)

**Documents tab:**
all documents details text boxes( set max length : 150 characters)

**Comment by phanibhushang** [comment]
Issue fixed.

**Comment by bhadra988** [comment]
Working fine
