### ISSUE TITLE
Student module(click on Bhadra student view button in manage student grid, student id: 134285) 

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#165]
In srr login-> manage students grid
when i'm clicked view button for student id: 134285(bhadra) in manage student grid, it gives server breakdown error

![image](https://user-images.githubusercontent.com/33898399/34639811-001cbd08-f29c-11e7-8c55-e84e5f9319ea.png)

![image](https://user-images.githubusercontent.com/33898399/34639842-7a02f268-f29c-11e7-86ac-568f6f70f690.png)

**Comment by phanibhushang** [comment]
in process

**Comment by phanibhushang** [comment]
Issue fixed. 
Sai, please look at stu_status table at apsams also. and make  this master table rows as active by making is_status=0

**Comment by bhadra988** [comment]
working good
