### ISSUE TITLE
Employee Module: Employeee_Basicinfo_Gender P3

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#17]
In employee module whenever we click on edit **selecting gender** as **_----select gender---_** it is updated it won't show gender column.

**Navigation**:Home/ Employee/ Manage Employees/ narendra k /Update Personal Details

![employee_basicinfo_gender](https://user-images.githubusercontent.com/33898412/33305770-6b6c25b0-d435-11e7-856e-ff75cdcf58ec.png)

**_Result_**:in **_updated_** view it wont show gender of an employee

**Comment by bhadra988** [comment]
working fine
