### ISSUE TITLE
Student module( percentage issue)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#171]
In student update Academic details having percentage text box, it accepted alpha numeric and other special characters, actually percentage should accepts floating and integer  numbers not more than 100 percentage

![image](https://user-images.githubusercontent.com/33898399/34665195-2051e476-f414-11e7-8926-ccf53e31c14c.png)

**Comment by Shiva578** [comment]
It's working fine

**Comment by bhadra988** [comment]
Working fine
