### ISSUE TITLE
Student Module(Date calendar not disappear ) 

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#181]
In student Academic tad having 3 date pickers all these having a common issue that is, date calendar is not disappear even i'm selecting date, it showing until i'm clicking any where in the page.

![image](https://user-images.githubusercontent.com/33898399/34771813-b9546804-f5ba-11e7-97b3-f8273ba97700.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by bhadra988** [comment]
working fine
