### ISSUE TITLE
Admin login (Configuration -> duplicate records gives server breakdown)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#183]
**In admin login->Home-> Configuration ->Document Category List**
First time we add one record like Aadharcard and after that delete that record and again add the record with the same name like Aadhracard and now click on create button it give ,**Integrity constraint violation – yii\db\IntegrityException**
refer following screen shots below.

![image](https://user-images.githubusercontent.com/33898399/34824974-79db802e-f685-11e7-863b-c7a83d46bf66.png)

![image](https://user-images.githubusercontent.com/33898399/34825081-eaa19956-f685-11e7-8bc2-46e40bab7db8.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by bhadra988** [comment]
Working fine
