### ISSUE TITLE
Employee module: apsams.in getting documents count wrong

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#192]
In employee module we have a tab called documents,in **samsindia.in** url it shows documents like below

![image](https://user-images.githubusercontent.com/33898412/35278776-05df70a4-0071-11e8-99d1-1461cfea2ec2.png)

But in **apsams.in** it shows only two documents as shown below
![image](https://user-images.githubusercontent.com/33898412/35278838-39d2334c-0071-11e8-8e1f-fbdd8ad9c3a3.png)

**Comment by bhadra988** [comment]
worked
