### ISSUE TITLE
student module(P1)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#2]
Navigation URL:  Home->Student->Manage Students->Krishanm Nalla(View any student profile) and click on Generate PDF button it will shows an error. please find the attachment of this error.

![generate pdf error 2](https://user-images.githubusercontent.com/33898399/33252428-08495a0e-d2f3-11e7-968d-2b00709f4a18.png)
![generate pdf error1](https://user-images.githubusercontent.com/33898399/33252429-08777a74-d2f3-11e7-8c7a-8a4af1cab75b.png)

Thanks & Regards.
Bhadra.

**Comment by pasha05** [comment]
inprogress [pasha]

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by bhadra988** [comment]
Again it shows the same error

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by bhadra988** [comment]
working fine
