### ISSUE TITLE
Configuration_Asset type, Dept test center

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#219]
In configuration-> when i'm clicking on Asset type and Dept Test Center it gives 404 error

![image](https://user-images.githubusercontent.com/33898399/37238778-800a35e6-23e2-11e8-83cc-89a56f2748d9.png)

![image](https://user-images.githubusercontent.com/33898399/37238784-8e3f62a8-23e2-11e8-9065-d9bc88803b04.png)

**Comment by Shiva578** [comment]
Working fine...!!!!
![image](https://user-images.githubusercontent.com/33898412/38367408-35b1862e-3900-11e8-8d5d-d22cc74efe10.png)
