### ISSUE TITLE
College profile:manage college grid getting exception while clicking empty row view icon

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#231]
In **college profile** while clicking on **manage college**  it shows **manage college grid** while clicking on empty row view icon we are getting Exception.

![image](https://user-images.githubusercontent.com/33898412/38172605-f453f51c-35cc-11e8-8cfa-d1b9d48e4073.png)

**Result**:

![image](https://user-images.githubusercontent.com/33898412/38172609-08cb5cb0-35cd-11e8-95b0-c60253f48a46.png)

**Comment by bhadra988** [comment]
working fine
