### ISSUE TITLE
Employee Module: Employee_Basic info_Personal Email P3 Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#24]
In employee module while editing employee records **personal email id** accepting alphanumeric values as well as special characters and it is not updated.

**_Navigation_**:  Home/ Employee/ Manage Employees /narendra k /Update Personal Details
![employee_basicinfo_personalemail](https://user-images.githubusercontent.com/33898412/33310177-becbac42-d446-11e7-917e-f2be1d6e2577.png)

**_Result_**:Personal email id not updated and it won't show any where.

**Comment by pasha05** [comment]
fixed [pasha]

**Comment by Shiva578** [comment]
working fine but it accepting special characters like 6384638$#%#5@gmail.ifgf.

**Comment by Shiva578** [comment]
working fine
