### ISSUE TITLE
Employee Module: Employee_Basic info_Employee Id P3 Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#27]
In employee module **_Employee Id_** accepting special characters and it is not updated any where.

Navigation:  Home/ Employee /Manage Employees /narendra k /Update Personal Details

![employee_basicinfo_empid](https://user-images.githubusercontent.com/33898412/33310504-d78c1126-d447-11e7-998e-b4154cbf7c31.png)

**Result**:it won't display any where.

**Comment by bhadra988** [comment]
working fine
