### ISSUE TITLE
Bug in student module

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#3]
![document1](https://user-images.githubusercontent.com/33898399/33252728-bb99df1a-d2f4-11e7-8d2b-f3d7e75d4346.png)
Home->Student->Manage Students->Krishanm Nalla(View any student profile), in Document section, i upload any document and later i'll try to delete it, then it will shows an error like below.
![document](https://user-images.githubusercontent.com/33898399/33252716-a550e8ac-d2f4-11e7-99a1-6cd1049c8896.png)

Thanks & Regards,
Bhadra.

**Comment by srinikoganti** [comment]
Nice start Bhadra...

**Comment by satyabratmishra** [comment]
Bug fixed, files uploaded to apsams
