### ISSUE TITLE
Employee module: Employee basic info_navigation P3 Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#31]
whenever we clicking on employee basic information, while editing  there is a button name called **back** while clicking on it. it will redirect to manage employees not to employee basic information(this issue same for **family info,address,personal info,academic & awards**)

![employee_basicinfo_navigation](https://user-images.githubusercontent.com/33898412/33314065-80481c38-d452-11e7-8ec5-9860155df541.png)

**Result**:Navigation issue

**Comment by bhadra988** [comment]
working good
