### ISSUE TITLE
Employee module:Emplloyee_Basic information_Aadhar(p3) Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#32]
Employee dependent information Aadhar number allows 4 digits. Data appeared in clumsy format,diff abled% it takes 789%

**Navigation**: Home/ Employee/ Manage Employees/ narendra k/ Update Family Details

![employee_basicinfo_aadhar](https://user-images.githubusercontent.com/33898412/33314523-e7106c80-d453-11e7-8991-fd7252decfcf.png)
**Result**: Aadhar number allows 4 digits numeric values

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by Shiva578** [comment]
working fine
