### ISSUE TITLE
Employee module: Employee_Personal info_(P1) Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#37]
In employee module while updating **_employee personal info_**/Bank details/Salary info it is throws an **_SQL Exception_** 

**_Navigation_**:Home /Employee /Manage Employees/ narendra k /Update Other Details

![employee_pesronalinfo_update](https://user-images.githubusercontent.com/33898412/33359110-fafad934-d4f2-11e7-92a0-ddb37444ce05.png)

**_Result_**:Geting Sql Exception While clicking on Update button in Employee Personal info

**Comment by pasha05** [comment]
inprogress [pasha]

**Comment by pasha05** [comment]
Fixed

**Comment by Shiva578** [comment]
In employee module while editing  personal info there is a column called salary info in that next increment date pick any date and click on update button it throws an SQL Exception

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by Shiva578** [comment]
working fine
