### ISSUE TITLE
Employee module:Employee_Awards_(P1)

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#38]
In **_employee module_** while updating **_employee awards_** it throws an **_SQL Exception_**

**_Navigation_**:http://apsams.in/web/index.php?r=employee%2Femp-master%2Fupdate&empid=9167&tab=AcademicsAwards

![employee_awards](https://user-images.githubusercontent.com/33898412/33359319-162be364-d4f4-11e7-9eb3-28be450fd53f.png)

**_Result_**:While updating employee awards it's getting an SQL exception.

**Comment by pasha05** [comment]
FIXED [pasha]

**Comment by phanibhushang** [comment]
we need exam center data, and missed data for "department tests". and now we won't get any errors page.

**Comment by Shiva578** [comment]
working fine
