### ISSUE TITLE
Employee Module  P1 Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#5]
In employee module while updating employee dependent info it will throws an SQL Exception like below

![employee_depenedentinfo_update](https://user-images.githubusercontent.com/33898412/33258325-31b428e2-d37f-11e7-8d8f-e091874dcc4e.png)

Thanks & regards,
Shiva.

**Comment by pasha05** [comment]
fixed

**Comment by bhadra988** [comment]
Not Fixed still existing in samsindia.in

**Comment by phanibhushang** [comment]
Issue fixed in samsindia.in, please check.
