### ISSUE TITLE
Student module

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#6]
Home->Student->Manage Students->Krishanm Nalla->Update Basic Details, mobile number text box accepting even 2 digits also. PFA.
![mobile_error](https://user-images.githubusercontent.com/33898399/33258586-fa42d3ec-d30e-11e7-8122-c935135e917e.png)

Thanks & Rehgards,
Bhadra.

**Comment by pasha05** [comment]
FIXED (in excel bug)

**Comment by bhadra988** [comment]
Partially fixed as it is having a problem with the copy the text from some where along with space followed by number, it is accepting as correct. But actually it should throw error message. Please refer below screen shots.
![mobile_err](https://user-images.githubusercontent.com/33898399/33883536-032481fc-def1-11e7-8809-f3a3e3239efe.png)

**Comment by bhadra988** [comment]
working fine in samsindia
