### ISSUE TITLE
Employee module:Excel button(P2)

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#67]
In employee module while clicking on Excel button the file downloaded in excel format but the name of the college shown different present i'm in **SRR & CVR College** login
**navigation**Home /Employee /Manage Employees

![emp_excel](https://user-images.githubusercontent.com/33898412/33761316-947d6f8a-dc2e-11e7-88ab-271a6ef1a08e.png)

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by Shiva578** [comment]
Working fine
