### ISSUE TITLE
Employee module:pdf generated time is mismatch(P2)

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#69]
In employee module while upload documents  and click on  **generate pdf** button it shows date time as 10:38:58 now it's 04:15pm
**navigation**:Home/ Employee/ Manage Employees/ K RAJESH
![emp_pdf_time](https://user-images.githubusercontent.com/33898412/33762729-a1bbf25c-dc33-11e7-9d35-2b75a85794f1.png)

**Comment by satyabratmishra** [comment]
Fixed

**Comment by Shiva578** [comment]
it displaying  11:19:35 now it's 04:25pm

**Comment by phanibhushang** [comment]
please recheck. i think issue is fixed.

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by Shiva578** [comment]
working fine
