### ISSUE TITLE
student module(student profile photo not uploading properly) 

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#72]
** Home ->Student ->Manage Students ->UMAKANTH PILLA**

I'm trying to upload student profile picture but picture is not coming.

![photo_error](https://user-images.githubusercontent.com/33898399/33818128-06aebc38-ddf8-11e7-9632-58e0c461ccce.png)

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by bhadra988** [comment]
Working fine
