### ISSUE TITLE
Employee module:Personal info_Update Button (P1) Bug

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#73]
In employee module while clicking on **employee personal info** click on **edit button** in that we have **salary info** just pick any date in next increment date then click on update button it throws an Sql Exception
![employee_personalinfo](https://user-images.githubusercontent.com/33898412/33818354-6042687c-de6a-11e7-8a2d-fd8deb5e3859.png)

![employee_salaryinfo](https://user-images.githubusercontent.com/33898412/33818427-dafe342e-de6a-11e7-838e-b75fb6ec0ac9.png)

**_Result_**:
![emp_p1](https://user-images.githubusercontent.com/33898412/33818446-fd1dfef4-de6a-11e7-9a9b-d44711ee60a2.png)

**Comment by satyabratmishra** [comment]
Bug Fixed

**Comment by Shiva578** [comment]
Working fine
