### ISSUE TITLE
Student Module

### ISSUE THREAD

**Issue by satyabratmishra** [srinikoganti/sams#75]
Navigation URL: Home->Student->Manage Students->Selecting Filter option from course filter it will shows an error. Please find the attachment of this error.
![error](https://user-images.githubusercontent.com/34025464/33827619-fb92e1e8-de8e-11e7-8cc9-22166440b6aa.png)

**Comment by satyabratmishra** [comment]
Bug fixed

**Comment by bhadra988** [comment]
working fine
