### ISSUE TITLE
Employee Module:Nominee info not updated (P1)

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#85]
In employee module **family info** tab there is a column called **nominee info** try to add some values and then delete nominee info it's not  going to updated in database again it shows nominee info.
**Navigation**: Home/ Employee/ Manage Employees/ narendra k
**Result**:
![emp_nominee info](https://user-images.githubusercontent.com/33898412/33879607-fc5603d2-df54-11e7-9991-122fbf0b113a.png)

**Comment by phanibhushang** [comment]
Issue fixed. and committed to git.

**Comment by Shiva578** [comment]
Working fine
