### ISSUE TITLE
Employee Module:Employee report shows wrong count( not set 1478) P3

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#88]
In employee module while clicking on employee tab employee designation wise report showing wrong count In SRR & CVR we have only 92 employees are there but in that employee report it shows (1478 not set).
**Navigation**:Home /Employee Module.
![employee report](https://user-images.githubusercontent.com/33898412/33939093-d03fd29c-e02f-11e7-8c66-ab119faa4a7c.png)

**Comment by phanibhushang** [comment]
issue fixed.

**Comment by Shiva578** [comment]
working fine
