### ISSUE TITLE
Employee module:Generate pdf getting error

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#89]
In employee module while clicking on **generate pdf** getting error whose employee not having  department.
**Navigation**:Home Employee/ Manage Employees /PALAKOLLU VENKATARAVAMMA
**Result**:
![generate pdf](https://user-images.githubusercontent.com/33898412/33976197-3a02beae-e0b9-11e7-8bb7-2de974566984.png)

**Comment by pasha05** [comment]
fixed

**Comment by Shiva578** [comment]
working fine.

**Comment by Shiva578** [comment]
**Employee whose not having department** while clicking on **search icon**  we have **generate pdf** button while clicking on it.it throws an SQL Exception.like below(Employee Id:7584)
![emp_genarate pdf](https://user-images.githubusercontent.com/33898412/34253975-dfc4ce66-e66f-11e7-9f15-4aa1c941ca5d.png)

**Comment by satyabratmishra** [comment]
Fixed
