### ISSUE TITLE
Employee module: navigation issue

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#90]
In employee module while adding employee below navigation
**Navigation**:Home /Employee /Manage Employee /Add Employee
while clicking on Manage employee it is redirecting to manage employee at present i'm in adding employee.
![navigation](https://user-images.githubusercontent.com/33898412/33977081-11c9619e-e0bf-11e7-8488-cd71ba002889.png)

**Result**: expecting this naviagtion **Home/ Employee/Add Employee**

**Comment by phanibhushang** [comment]
It is not an issue. please close.

**Comment by Shiva578** [comment]
okay sure sir
