### ISSUE TITLE
Employee module:Family info_Dependent  information

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#91]
In employee module click on manage employee edit the employee whose not having any department. while clicking on **family info** tab try to add employee **dependent information** fields.it throws an SQL Exception.
**Navigation**:Home /Employee /Manage Employees/ PALAKOLLU VENKATARAVAMMA
![emp_dependent info](https://user-images.githubusercontent.com/33898412/33978946-1b2afc80-e0c8-11e7-86fb-54315b30e6c5.png)

**Comment by pasha05** [comment]
fixed

**Comment by Shiva578** [comment]
working fine
