### ISSUE TITLE
Employee Module:personal info mobile number accepting wrong format

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#94]
In employee module while editing employee basic info in personal details mobile number and personal mobile number accepts spaces when we copy and paste it in mobile number text box like below
**Navigation**:Home /Employee /Manage Employees/ narendra k Update Personal Details
**Result**:
![personal_mobile](https://user-images.githubusercontent.com/33898412/33985349-53055da4-e0e0-11e7-86e5-3c28662d47f7.png)

**Comment by pasha05** [comment]
issue fixed here.

Please provide other places also where we need to change. please provide the list where this type of errors should not occur.

**Comment by Shiva578** [comment]
Whenever we enter personal mobile number it taken previous mobile number as personal number example i entered 9848012345 it replace with above mobile number 45.

**Comment by pasha05** [comment]
it is working fine

![image](https://user-images.githubusercontent.com/34034873/34169156-7361e236-e50c-11e7-9d78-b7691bd1ec40.png)

**Comment by Shiva578** [comment]
in employee personal mobile number we enter 45 and press tab button it takes mobile number as 9908282581.mobile number and personal mobile number it takes same number instead of entered number

**Comment by Shiva578** [comment]
whatever value we entered in personal mobile number it wont taking(45) it  replace with  mobile number(9848012345) while clicking tab button after enter the value 45.

**Comment by pasha05** [comment]
inprocess

**Comment by Shiva578** [comment]
working fine
