### ISSUE TITLE
Student module

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#95]
**Home-> Student-> Manage Students-> BABU MARKAPUDI-> Update Academic Details**

When i'm updating the student academic details, i'm selecting the student  **Is Status** is in-active state and updated, but in display it's showing Active state and again i'm rechecking the updated details in updated academic info **Is Status** become Active state.
![is status_error](https://user-images.githubusercontent.com/33898399/33985973-0259d1ce-e071-11e7-96a9-a682aa5c3afc.png)
![is status1_erro](https://user-images.githubusercontent.com/33898399/33985974-028afa92-e071-11e7-95f6-2400e7f75b5e.png)
![is status2_error](https://user-images.githubusercontent.com/33898399/33985976-02b8530c-e071-11e7-96ec-f55327a27984.png)

**Comment by satyabratmishra** [comment]
Bug Fixed. Status removed from this page and added in basic info page

**Comment by bhadra988** [comment]
**Home ->Student-> Manage Students ->siva sundaram satyam siam ->Update Basic Details**
In student basic information profile, when we select **Is Status** Active or InActive working fine, but if i'm not select any of these two and click on update it gives **Integrity constraint violation – yii\db\IntegrityException**.

![is status_error3](https://user-images.githubusercontent.com/33898399/34372241-332da76e-ea88-11e7-9b9b-955ae4704c90.png)
![is status_error4](https://user-images.githubusercontent.com/33898399/34372242-3356158c-ea88-11e7-8d75-25a0f013b99c.png)

**Comment by bhadra988** [comment]
Not fixed

**Comment by bhadra988** [comment]
working fine
