### ISSUE TITLE
Employee module:navigation problem

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#96]
In **employee module** while clicking on edit icon there is a tab called **personal info** in that we have one **back button** is appeared while clicking on it it will redirect to manage employees grid like below
**Navigation**:Home/ Employee /Manage Employees /narendra k Update Other Details
**Result**:
![nvaigation_back button](https://user-images.githubusercontent.com/33898412/33987513-233677be-e0e7-11e7-90a8-e1ac03e2aedc.png)

**Comment by phanibhushang** [comment]
issue fixed in #149

**Comment by Shiva578** [comment]
working fine
